name = "poet"
version = "0.1.0"

[dependencies]
maybe-utils = "git@github.com:tylanphear/maybe-utils|latest"
stanza-toml = "git@github.com:tylanphear/stanza-toml|latest"
semver = "git@github.com:tylanphear/semver|0.1.1"
